# Generated by Django 3.2.5 on 2021-07-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_band_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
